version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '20:00'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "typeorm*"
      - dependency-name: "@heroicons/react"
      - dependency-name: "@nestjs/typeorm"
